# This is a basic workflow to help you get started with Actions

name: Checkout

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Clone private repo
      run: git clone https://ejarte:${{ secrets.TOKEN }}@gits-15.sys.kth.se/Kaleidoscope/Web.git

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y tree

    - name: see code
      run: tree


    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    - name: push
      run: |
          cd Web
          git remote set-url origin https://ejarte:${{ github.TOKEN }}@git@github.com:ejarte/webhook.git
          git push -f

